### ISSUE TITLE
Left menu panels too big and won't resize when specviz window has mouse focus

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#552] opened 2019-03-11 18:23 UTC
I didn't see this issue in working with other cubes, but when working with Bethan James's SINFONI cube, if I move the mouse focus to the specviz window I get an enormous left-panel menu. And the handle for dragging it smaller doesn't work. Or rather, it will make the window disappear (after some lag) if I drag it all the way to the left. But it won't resize somewhere in between.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/2261329/54147780-44bad480-4409-11e9-9267-9ea4e2feb97e.png">

**Comment by hcferguson** [comment] 2019-03-11 18:26
Also, toggling on and off the overlays in the specviz plot are not working for this data set. But are working for other data sets I've tried.

**Comment by hcferguson** [comment] 2019-03-13 14:18
Even worse funky resizing when using a different data set: kmos: FLAMES_Haro11_L6_cube_bjames

**Comment by nmearl** [comment] 2019-03-13 15:35
I believe this is happening because of an incorrect parsing of the fits attributes. You can see that the the dropdown menu for `attribute` in the sidebar is trying to show the entire path of the data file. Generally, this would just be a drop down for `flux`/`wavelength`/`pixel`/etc.

The issue seems two fold: 1) the widget shouldn't be resizing in response to the items its holding (a glue issue); and 2) the attributes of the data file are super weird.

**Comment by astrofrog** [comment] 2019-03-21 09:53
> 1) the widget shouldn't be resizing in response to the items its holding (a glue issue)

I believe the issue is that the combo box in the specviz layer options should have the ``AdjustToMinimumContentsLength`` policy set. All combo boxes in glue have this set to avoid this kind of issue.

**Comment by brechmos-stsci** [comment] 2019-03-22 13:23
@astrofrog If this is a specviz issue, could you open one and then link back here.

**Comment by nmearl** [comment] 2019-03-22 15:49
This is fixed in my fork. You can test it out with `pip install git+https://github.com/nmearl/specviz`

**Comment by hcferguson** [comment] 2019-03-22 17:27
Seems to have done the trick!

**Comment by brechmos-stsci** [comment] 2019-03-25 13:34
@nmearl, will you be releasing a new specviz that includes this fix?

**Closed** 2021-07-20 18:42 UTC
Labels: won't fix
