### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#278] opened 2018-03-09 04:37 UTC
(Apologies in advance if some of these features are not supposed to work yet.)

v0.1.dev534

Region selection doesn't work with the MaNGA cube I've loaded.
* DRD: this was due to an issue between (slightly) older versions of glue and cubeviz. It should be fixed by #289 

Can select a ROI in SpecViz, but cannot Apply to Cube.
  * CKJ: The "Apply to Cube" is for things like smoothing operations

Data Processing -> Collapse Cube doesn't seem to do anything.
  * CKJ: I think this is an "old version" issue

"a" and "d" hot keys don't change the slice displayed.
"f" for freezing doesn't seem to work. same for "p" for pull
  * CKJ: It worked for me, I think you have an older version...

**When I have a dialog box displayed and I click outside of
glue, the box disappears.  Whenn I click back in glue, it appears again.**
  * DRD: Opened issue #320 to track this.

**View -> Wavelength Units: When I change the units the spectrum
display shows a super large range, including wavelengths where
there are no data.  Also, this causes the the IVAR and MASK cubes
to rescale so that they are both all black.  Same thing happens
if I choose other options in this menu other than Angstroms.**
  * CKJ: There is a ticket #137, I started working on this one

If I choose mm, the spectrum disappears entirely.
  * CKJ: I don't see that, but it is probably related to #137 

**View -> RA - Spectral and DEC - Spectral don't seem to do anything.**
  * CKJ: Those are now removed from the menu and will be implemented "later".

**Data Processing -> Arithmetic Operations
TEST2 = FLUX + 100
However, the spectrum doesn't seem to reflect this change.**
  * CKJ: @kassin Did you want a new spectrum to be displayed?

**The Save Dialog box makes it looks like I will overwrite the currently loaded
cube.  Phew, I hit "OK" and see this is not the case now.  The saved file
has no suffix if I don't type one.  Perhaps we should automatically append one?**
    * CKJ: Opened a ticket #324

**If I save a single smoothed component (as a single componet cube with no ivar or mask) and read it into a fresh glue session, it loads the component in all three viewers.  It should only display it in one viewer.**
  * CKJ: This is the current way it happens. When we have time to re-org the GUI it will only bring up one image viewer.

**Unable to save session.  The error is: "Failed to save session
Don't know how to serialize <cubeviz.data_factories.DataConfiguration object at 0x18335e6748> of type <class 'cubeviz.data_factories.DataConfiguration'>"**
    * CKJ: @kassin it works fine for me, could you reproduce and add more information here?

Smoothing

**-"Info: Smoothing previews are displayed on CubeViz's left and single image viewers."  Since we will eventually allow the users to move the viewers around,
and some users may be unsure about what the single image viewer is,
hwo about stating something like this instead: "A preview of the
smoothing operation is displayed in Viewer 1."**
  * CKJ: 

**-We need to state somewhere that the preview smooths the one channel
displayed, and clicking on "okay" smooths the entire cube.**
  * CKJ: I opened https://github.com/spacetelescope/cubeviz/issues/325

Contours

**-Perhaps change "Custom Component" to "Other Component" because custom
implies that the user can create this component somehow.**
  * CKJ: Fixed by #307 

Viewer Options

**-scaling (ie slider bar next to "color/opacity) in the viewer options panel)
shouldn't bee linked across the 3 viewers as a default**
  * CKJ: Created https://github.com/spacetelescope/cubeviz/issues/326

**-I can't think of a use case where one would want to scale the 3 viewers
at the same time, so perhaps remove the "sync" button.**
  * CKJ: Added comment to #326

**-For playing movie to run through channels, can I change the speed?**
  * CKJ: That is a glue thing, not sure about speed on there. 

**-The "limits" in "Plot Options - 2D Image" don't seem useful since they
don't correspond to the limits shown on the image.**
  * CKJ: Created https://github.com/spacetelescope/cubeviz/issues/327  they seem to be pixel values as they change when I zoom in the image.

**-If I change the limits, I cannot undo it using the Edit -> Undo option.**
  * CKJ: Correct, but you can Hit the "Home" button in the image view.  Though that does not seem obvious to users.

@brechmos-stsci @drdavella @astrofrog @robelgeda @javerbukh

**Comment by brechmos-stsci** [comment] 2018-03-09 14:33
I'll go through this list and check things.

**Comment by charlottenosam** [comment] 2018-03-12 05:02
Here are my testing notes on **v0.1.dev540**, following the items in #257 

* Load your favorite datasets
	- KMOS cubes only have 2 extensions (data + noise) but the loader loads 3 views (1x data + 2x noise). It would make sense to leave the 3rd viewer blank if there is so extension
* Spatial smoothing
 	- All good (I like the preview!)
* Spectral smoothing
	- The smoothing kernel needs units. I *think* it's currently pixels but I'm not sure...
	- It would be great to have an option to plot a smoothed spectrum weighted by the inverse variance (from the noise cube). This is useful to smooth out bright skylines in near-IR observations
* Cube collapsing over wavelength ranges
	- Worked fine, though it would be nice if the smoothed cube appeared automatically in one of the viewers
* Basic image control (moving through slices, overlays etc)
	- Would it be possible to show 2D ROIs as a contour? I.e. have the option to show only the edges rather than the whole ROI
	- Under contour options show the default parameters (at the moment everything is = 0)
	- Hovering over 2D viewer, pixel values (~1E-20) show as 0.000 --> need to display in scientific notation
	- Hot keys a, d, f and p work for me
* Interaction with 1D spectra functionality
	- I still can't see a line showing which wavelength position the 2D viewer is at
	- When hovering can you show the wavelength pixel as well as physical units?
	- If you drag an ROI in specviz which was already linked to a cubeviz viewer component to a new wavelength position, I think that the 2D viewer should move automatically to the new position.
* Save calculated data
	- At the moment unless you type the file extension it doesn't add one (might be a MacOS High Sierra thing)
	- I don't understand what saving a subset does. I thought it might zero all the flux outside the ROI for example, but it didn't seem to do anything.
	- You can save the 2D viewers as images, is it also possible to save them as 2D fits files?
	- Can you save 1D spectra from specviz as fits/txt AND as images?

**Comment by hcferguson** [comment] 2019-02-08 19:27
@kassin can this issue be closed?

**Comment by kassin** [comment] 2019-02-11 02:36
Not until Charlotte & I are able to run our use cases through CubeViz.

**Comment by brechmos-stsci** [comment] 2019-03-05 16:12
From @kassin's comments above.  These are all fixed, worked or I created an issue.

* Region selection doesn't work with the MaNGA cube I've loaded.
  * works for me

* Can select a ROI in SpecViz, but cannot Apply to Cube.
  * The "Apply to Cube" is for things like smoothing operations

* Data Processing -> Collapse Cube doesn't seem to do anything.
  * worked for me

* "a" and "d" hot keys don't change the slice displayed.
* "f" for freezing doesn't seem to work. same for "p" for pull
  * all worked for me

* When I have a dialog box displayed and I click outside of glue, the box disappears. Whenn I click back in glue, it appears again.
  * Issue #320 to track this.

* View -> Wavelength Units: When I change the units the spectrum display shows a super large range, including wavelengths where there are no data. Also, this causes the the IVAR and MASK cubes to rescale so that they are both all black. Same thing happens if I choose other options in this menu other than Angstroms.
  * This seems to be fine, but found another bug https://github.com/spacetelescope/specviz/issues/683

* If I choose mm, the spectrum disappears entirely.
  * The rescaling appears to be working, but see above bug.

* View -> RA - Spectral and DEC - Spectral don't seem to do anything.
  * Those are now removed from the menu and will be implemented "later".

* Data Processing -> Arithmetic Operation TEST2 = FLUX + 100 However, the spectrum doesn't seem to reflect this change.
  * this work, just a matter of intent in specviz on arithemetic operations. Currently a new spectrum is not displayed

* The Save Dialog box makes it looks like I will overwrite the currently loaded cube. Phew, I hit "OK" and see this is not the case now. The saved file has no suffix if I don't type one. Perhaps we should automatically append one?
  * Fixed in #324

* If I save a single smoothed component (as a single componet cube with no ivar or mask) and read it into a fresh glue session, it loads the component in all three viewers. It should only display it in one viewer.
  * This is the current way it happens. When we have time to re-org the GUI it will only bring up one image viewer.

* Unable to save session. The error is: "Failed to save session
Don't know how to serialize <cubeviz.data_factories.DataConfiguration object at 0x18335e6748> of type <class 'cubeviz.data_factories.DataConfiguration'>"
  * This is still a current issue (created a ticket https://github.com/spacetelescope/cubeviz/issues/519)

Smoothing

* "Info: Smoothing previews are displayed on CubeViz's left and single image viewers." Since we will eventually allow the users to move the viewers around, and some users may be unsure about what the single image viewer is, hwo about stating something like this instead: "A preview of the smoothing operation is displayed in Viewer 1."
  * This now states "can be selected in the viewer drop-down menu"

* We need to state somewhere that the preview smooths the one channel displayed, and clicking on "okay" smooths the entire cube.
  * This was fixed https://github.com/spacetelescope/cubeviz/pull/336

Contours
* Perhaps change "Custom Component" to "Other Component" because custom
implies that the user can create this component somehow.
  * Fixed by #307

Viewer Options

* scaling (ie slider bar next to "color/opacity) in the viewer options panel) shouldn't bee linked across the 3 viewers as a default
  * Fixed in https://github.com/spacetelescope/cubeviz/pull/384

* I can't think of a use case where one would want to scale the 3 viewers at the same time, so perhaps remove the "sync" button.
  * Fixed in https://github.com/spacetelescope/cubeviz/pull/384

* For playing movie to run through channels, can I change the speed?
  * That is a glue thing, not sure about speed on there.  Would have to open a ticket in glue

* The "limits" in "Plot Options - 2D Image" don't seem useful since they don't correspond to the limits shown on the image.
  * Discussion on https://github.com/spacetelescope/cubeviz/issues/327 not a bug

* If I change the limits, I cannot undo it using the Edit -> Undo option.
  * The Edit -> Undo does not seem to be selectable given changes for limits etc.  So, I think this is a Glue thing. It is probably fine with the way it is and think about how "Undo" might work.  Or, maybe, could just remove the Undo menu.

**Comment by brechmos-stsci** [comment] 2019-03-05 17:00
From @charlottenosam's comments above:

*  Load your favorite datasets
        KMOS cubes only have 2 extensions (data + noise) but the loader loads 3 views (1x data + 2x noise). It would make sense to leave the 3rd viewer blank if there is so extension
  * This would be part of a "free the viewers" set of work https://github.com/spacetelescope/cubeviz/issues/304

* The smoothing kernel needs units. I think it's currently pixels but I'm not sure...
  * Appears to be fixed in https://github.com/spacetelescope/specviz/pull/395

* It would be great to have an option to plot a smoothed spectrum weighted by the inverse variance (from the noise cube). This is useful to smooth out bright skylines in near-IR observations
  * This should now be possible: Create a smoothed cube, use the arithmetic operation to divide by the IVAR though there is a bug report for the last step for the calculated arithmetic operation to be displayed as a spectrum.

* Cube collapsing over wavelength ranges Worked fine, though it would be nice if the smoothed cube appeared automatically in one of the viewers
  * This works now

* Basic image control (moving through slices, overlays etc)
  * Would it be possible to show 2D ROIs as a contour? I.e. have the option to show only the edges rather than the whole ROI
    * not currently an 

  * Under contour options show the default parameters (at the moment everything is = 0)
    * This does have proper default parameters

  * Hovering over 2D viewer, pixel values (~1E-20) show as 0.000 --> need to display in scientific notation
    * they are now in scientific notation
 
* Interaction with 1D spectra functionality 
  * It isn't possible to change flux units
    * Works now...
  * I still can't see a line showing which wavelength position the 2D viewer is at
    * this works

  * When hovering can you show the wavelength pixel as well as physical units?
    * this works (if there are units in the input file)

  * If you drag an ROI in specviz which was already linked to a cubeviz viewer component to a new wavelength position, I think that the 2D viewer should move automatically to the new position.
    * Once a collapsed cube is created from a spectral region, by design, the cube is not updated.  If this is desired, then we will have to work on it (@hcferguson  @kassin)

* Save calculated data
  * At the moment unless you type the file extension it doesn't add one (might be a MacOS High Sierra thing)
    * I believe that is a glue thing but will discuss with @astrofrog 

  * I don't understand what saving a subset does. I thought it might zero all the flux outside the ROI for example, but it didn't seem to do anything.
    * It does seem to save a FITS file (if fits is selected), but the extension is missing, as noted above.

  * You can save the 2D viewers as images, is it also possible to save them as 2D fits files?
    * Saving appears to work (though must specify the extension)

  * Can you save 1D spectra from specviz as fits/txt AND as images?
    * I don't see how to and the export button doesn't seem to do anything, opened a SpecViz ticket https://github.com/spacetelescope/specviz/issues/685

**Comment by brechmos-stsci** [comment] 2019-03-05 20:14
Discussed with @hcferguson and we are good to close this.

**Closed by brechmos-stsci** 2019-03-05 20:14 UTC
Labels: 1 day, medium-priority, scope-8
