### ISSUE TITLE
Setup bug

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/cubeviz#268] opened 2018-03-04 07:35 UTC
I was using CubeViz on my personal machine and this came up. I have been seeing it on my ST laptop as well. This happens when I run `python setup.py install` but when I run it a second time it works fine. Not sure what is going on, here is what the error says:
```
Freezing version number to ./cubeviz/version.py
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    get_debug_option(PACKAGENAME))
  File "/home/robel/projects/cubeviz/cubeviz/astropy_helpers/astropy_helpers/version_helpers.py", line 271, in generate_version_py
    imp.reload(version_module)
  File "/home/robel/miniconda3/envs/astroconda/lib/python3.5/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/robel/miniconda3/envs/astroconda/lib/python3.5/importlib/__init__.py", line 159, in reload
    name=parent_name) from None
ImportError: parent 'cubeviz' not in sys.modules

```

**Comment by robelgeda** [comment] 2018-03-04 07:40
It might have something to do with `astropy_helpers`

**Comment by drdavella** [comment] 2018-03-05 13:43
I suspect that after you did this once, if you tried to do it again, it would have worked fine. You're right that it has something to do with `astropy_helpers`. I've been meaning to look into it more closely, I'll try to find time during the sprint.

**Comment by drdavella** [comment] 2018-03-19 16:46
@robelgeda I am no longer able to reproduce this. I think it may have been fixed by the `astropy_helpers` update. I'm closing for now but if you experience it again please reopen.

**Comment by robelgeda** [comment] 2018-03-19 21:40
Thanks

**Comment by drdavella** [comment] 2018-04-09 15:42
@astrofrog reported this again and I think we might understand the root cause now. Reopening until a fix is submitted.

**Closed** 2018-04-10 16:47 UTC
Labels: bug
