### ISSUE TITLE
v0.3 release dependencies

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#470] opened 2019-02-05 16:09 UTC
As part of the v0.3 release and after some discussion about package dependencies with @drdavella we will need to come up with a set of minimum versions (or ranges) for cubeviz dependencies.  Then the following files will have to be updated based on the decisions. 

- [ ] Update setup.cfg
- [ ] Update .travis.yml
- [ ] Update astroconda cubeviz build recipe

Packages and versions to consider:

* Python = 3.6 or Python = 3.7
 * astropy ( ver ?)
 * glue-core 0.13.x or 0.14.x (?)
 * numpy (>= 1.13) ?
 * specviz 0.6.x (?)
 * spectral-cube >=0.4.2 (?)
 * matplotlib
 * asdf

The above dependencies will need to be checked with Joe to make sure they are available in the astroconda release, too.  Once they are decided then the above files will need to be updated.

**Comment by brechmos-stsci** [comment] 2019-02-12 18:58
I did a quick check and [anaconda has gluecore 0.14.1 in it](https://anaconda.org/anaconda/glue-core), so we should be good to use Anaconda as the distribution. 

In the past we needed a quick release from @astrofrog that did not get up onto Anaconda for *weeks* which is why we had to go use glueviz conda channel.  So, at least on that package, we are good with Anaconda.

**Comment by astrofrog** [comment] 2019-02-12 19:55
Just a quick note that unless I manage to fix compatibility with the developer version of glue in time for this release, we should also preemptively pin glue-core to <0.15 at the upper end.

**Comment by brechmos-stsci** [comment] 2019-02-13 13:28
@astrofrog That is the current plan. We are going to most likely have glue-core >= 0.13 and work only with released versions. There is a debate about pinning on the upper end, so that will be talked about in the next couple days. But thanks for the heads-up.

**Comment by brechmos-stsci** [comment] 2019-02-14 14:43
After a discussion between @drdavella we settled in on this list of dependencies:
```
python >= 3.6
glue-core >= 0.13, <0.15
astropy ( specviz/specutils requires >= 3.1 but we aren't going to pin it) 
numpy (some dependencies require >= 1.13, but we don't have a dependency on it, so no pin)                                  
specviz >= 0.7
spectral-cube >= 0.4.2 (not 100% sure on this but given it is pre 1.0 release we'll leave this here)
matplotlib
pyqt5
qtpy
pyyaml
scipy
```

**Comment by brechmos-stsci** [comment] 2019-02-14 14:59
Anaconda has:
glue-core 0.14.1 on anaconda/glue-core

all the others should be fine as we don't require anything super new for matplotlib etc etc

spectral-cube is not in anaconda but is in astroconda. In astroconda it is 0.4.3 so we are good there.
specutils is not in anaconda but is in astroconda. In astroconda it is 0.5.1 which should be good.

specviz will have to be updated in astroconda when it is released

So, we should be good for all our dependencies for conda-ish stuff (once specviz is updated in astroconda).

**Comment by hcferguson** [comment] 2019-02-14 15:06
Just so I understand the implications here....when something is set to >= XX does this imply that we are regression-testing with XX and with the current development version (e.g. Astropy GitHub master?).

**Comment by brechmos-stsci** [comment] 2019-02-14 15:11
The ones above are the install dependencies. The tox testing matrix that @drdavella setup has it testing against the latest released version and the dev versions of some packages (e.g., astropy, numpy).  But the tests against the dev versions are allowed to fail.

So, I guess the question is whether we test against XX, latest release, and dev version. I would have to look through the tox env (or ask @drdavella) about the test against XX if not the latest release.

**Comment by astrofrog** [comment] 2019-02-14 17:33
I think we'd need to explicitly say that we want to test against the oldest compatible version, otherwise it will test against the latest stable version. See https://github.com/spacetelescope/cubeviz/issues/489 for a suggestion of making a 'legacy' configuration.

**Comment by brechmos-stsci** [comment] 2019-02-15 12:36
@astrofrog Yeah, that's what I meant, maybe just wasn't clear.

**Comment by drdavella** [comment] 2019-03-06 14:44
Closing since this is overcome by #477 (which updated the `specviz` dependency) and #516 (which makes `cubeviz` entirely pip-installable).

PR #524 updates our CI test matrix to make sure we are testing against Py37 (which is possible now thanks to #477), and also removes some previously allowed failures.

**Closed** 2019-03-06 14:44 UTC
Labels: 0.5 days, discussion, high-priority
