### ISSUE TITLE
Test Import Wizard with new and existing IFU Cubes

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#73] opened 2017-10-18 12:29 UTC
SK
David contacted many IFU teams about header keywords.
Will talk with pipeline working group for JW.
Goal is to have standard keywords.

DL
In contact with SDSS/MaNGA, SAMI, CALIFA, ATLAS-3D, GPI, KMOS, MUSE.

SK
David is writing a technical report on this

Imported from Trello https://trello.com/c/1b8CBz3g

**Comment by brechmos-stsci** [comment] 2017-10-25 16:49
@astrofrog please create an import wizard for cubeviz.

**Comment by brechmos-stsci** [comment] 2017-12-18 20:48
@kassin We need more users to upload their cubes or send you cubes to test the import features.  List the IFU cubes here which are working or not working so we know...

**Comment by brechmos-stsci** [comment] 2018-01-03 14:47
@kassin @drlaw1558 Would you be able to either test the loading of known IFU cubes, or ask the users to try loading them. Then if there are issues, maybe post here with a location of the data so we can make fixes to the loader/importer.

**Comment by kassin** [comment] 2018-01-04 19:08
This is a new data cube I placed in /astro/3/jwst_da_sprint_testdata/IFU_datacubes/KMOS_Mason
It is of a high redshift galaxy observed with the KMOS IFU on the VLT telescope.  Please do not share!  This reads in well.

**Comment by kassin** [comment] 2018-01-04 19:22
Not sure what you mean by input wizard.  Do you mean the "Open Data" option?  Or do you mean a wizard button like in SpecViz?  I assume the former.

**Comment by kassin** [comment] 2018-01-04 19:23
The data cube at /astro/3/jwst_da_sprint_testdata/IFU_datacubes/MUSE/DATACUBE_HDFS_v1p0.fits.gz doesn't read in.  If I select the KMOS data reader it sort of reads in, but SpecViz doesn't work.  Note that this data cube is 2.6G!!

**Comment by kassin** [comment] 2018-01-04 19:31
I can't seem to load Bethan's SINFONI data cube:
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/SINFONI/SINFONI_CAS64_k_bjames.fits

**Comment by drdavella** [comment] 2018-01-04 19:34
@kassin I'll try to take a look at these tomorrow and see if I can update the data loaders to accommodate these files.

**Comment by kassin** [comment] 2018-01-04 20:44
@drlaw1558 for the MIRI simulated data cube at:
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/MIRI_Simulated/level3/single_ch1-2-short_s3d.fits
there doesn't seem to be error and DQ extensions.  Or at least I can't locate them.

**Comment by kassin** [comment] 2018-01-04 20:47
Can't get the FLAMES data cubes from Bethan to read in:
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/FLAMES/FLAMES_Haro11_L6_cube_bjames.fits
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/FLAMES/FLAMES_Haro11_L6_cubeerr_bjames.fits

**Comment by kassin** [comment] 2018-01-04 20:50
Can't get the CWI data cube to read in:
/astro/3/jwst_da_sprint_testdata/IFU_datacubes/CWI/image13657_icuber.fits

**Comment by brechmos-stsci** [comment] 2018-01-22 19:32
With the current version (I am now at 0.1dev282)...

Works:  /astro/3/jwst_da_sprint_testdata/IFU_datacubes/KMOS_Simona/singlecubes/ifu10_ifu10.fits
![image](https://user-images.githubusercontent.com/18348847/35240034-2eebbabc-ff80-11e7-89f9-7081f3d5a350.png)

/astro/3/jwst_da_sprint_testdata/IFU_datacubes/KMOS/SCI-GUM43_SCI_COMBINED_7.fits
![image](https://user-images.githubusercontent.com/18348847/35240066-4dcbba5e-ff80-11e7-8526-762fcf1f404b.png)

Currently have issues:
* /astro/3/jwst_da_sprint_testdata/IFU_datacubes/MUSE/DATACUBE_HDFS_v1p0.fits.gz
* /astro/3/jwst_da_sprint_testdata/IFU_datacubes/KCWI/	
  * kb170517_00151_icubes.fits 
  * kb170517_00151_mcubes.fits 
  * kb170517_00151_vcubes.fits

**Comment by brechmos-stsci** [comment] 2018-01-22 19:54
@kassin We are not currently setup to load FLUX, ERROR and DQ from separate files (e.g., the CWI/KCWI).  Is that something that needs to be expected, or can we require that a FITS file contains all three extensions?

**Comment by brechmos-stsci** [comment] 2018-01-22 20:00
@kassin The MUSE dataset above does not have "INSTRUME" = "MUSE" in the header.  

Is that something that we can require with the default configuration?  (Someone with a muse dataset can always load it be creating a new data configuration file, so it would be reasonable to say yes). 

@bethanjames

**Comment by kassin** [comment] 2018-01-22 21:29
Re KCWI/CWI: I'm afraid we need to be able to read in FLUX, ERROR, and DQ from separate files since they are not giving combined cubes.  Or, if you prefer, we can create code to combine the CWI/KCWI cubes.

Re MUSE: Unfortunately, we cannot require that pipelines that we don't have control over will use specific key header words.  I suggest we identify the MUSE cubes through the NAXIS1, NAXIS2, and NAXIS3 key header words.  These are the number of elements in each axis, something which should be specific to a given IFU.

**Comment by brechmos-stsci** [comment] 2018-01-23 14:30
@kassin Ok, this is interesting. I think what we should do is change the loading from the command line to allow loading any number of fits files (for now assuming they are all the same shape.  This will allow loading of an original FITS file and a saved, smoothed FITS file. 

A second point, currently we are loading data into cubeviz and mapping each component to FLUX, ERROR or DQ.  Given the usability above it probably makes more sense to map the name of the component straight from the EXTNAMEs in the FITS files.  Is there a reason we didn't do this in the first place?  From an astronomer point-of-view I think it makes more sense to label the component names in cubeviz by the extension name in the fits file.

RFC @kassin @hcferguson @bethanjames

**Comment by smei100** [comment] 2018-01-23 16:06
It is interesting I tried the KMOS file and I cannot open it. I have blank in the three viewer windows and no spectra.  What could the cause be?

**Comment by smei100** [comment] 2018-01-23 16:17
I have uploaded the KMOS single IFU data, and the manga test data. 
On the upper left, when I click on the ifu10... dataset, I still have the manga data displayed. See attached image
I am wondering if for some reason the cubeviz version that I have is not right. I have repeated the installation steps from 'source activate cubeviz-testing' on, but nothing changes

![screen shot 2018-01-23 at 5 12 47 pm](https://user-images.githubusercontent.com/24240692/35286806-3f54ddf2-0061-11e8-8067-fc44d4345484.png)

**Comment by brechmos-stsci** [comment] 2018-01-23 16:17
@smei100 I suspect you are using a slightly older version of cubeviz. I think the easiest thing to do, for now, is to create a new environment using the same instructions you did previously.  We need to create a simple way for you to **update** the development conda environment. So... sorry, but create a new conda environment.  One note on this, with the update you will now see the cubeviz version at the top of the cubeviz window (e.g., 0.1dev282).  In the future it will be easier to talk about versions :-)

**Comment by kassin** [comment] 2018-01-23 16:28
As per Craig's comment:

"A second point, currently we are loading data into cubeviz and mapping each component to FLUX, ERROR or DQ. Given the usability above it probably makes more sense to map the name of the component straight from the EXTNAMEs in the FITS files. Is there a reason we didn't do this in the first place? From an astronomer point-of-view I think it makes more sense to label the component names in cubeviz by the extension name in the fits file."

Yes, the name of the component in the fits file should be used.  I (mistakenly) thought this is what we were doing. :)

**Comment by smei100** [comment] 2018-01-23 16:36
Thank you Craig. I installed a new environment and it works. I can see the version number, I can open the KMOS IFU and also visualize different datasets clicking on the top bar.

**Comment by SaOgaz** [comment] 2019-03-06 16:45
@brechmos-stsci. this is for an older version of cubeviz right? Can I close this tickets?

**Closed** 2021-07-20 18:44 UTC
Labels: gui, in-progress, won't fix
