### ISSUE TITLE
Saving Cubes

### ISSUE THREAD

**Issue by kassin** [spacetelescope/cubeviz#195] opened 2018-01-25 19:30 UTC
Users would like the ability to save a cube to disk.

@brechmos-stsci @astrofrog

**Comment by brechmos-stsci** [comment] 2018-01-29 13:28
@astrofrog  Is this functionality available through the Glue framework?

**Comment by astrofrog** [comment] 2018-02-06 13:39
As mentioned on the tag-up yesterday, this is accessible by control-clicking on the name of a dataset and selecting 'Export data values':

<img width="376" alt="screen shot 2018-02-06 at 13 37 39" src="https://user-images.githubusercontent.com/314716/35862302-1886b7c6-0b43-11e8-9aaa-54dabd28a81f.png">

It would be easy to tap into this functionality by adding a button to the cubeviz UI. I can try and open a PR for this.

**Comment by astrofrog** [comment] 2018-02-06 13:39
Also, this appears to be a duplicate of https://github.com/spacetelescope/cubeviz/issues/174 so one of these should be closed

**Comment by brechmos-stsci** [comment] 2018-02-06 15:24
I think what might make sense is to have a "Save Data" button beside the "Open Data" button:
![image](https://user-images.githubusercontent.com/18348847/35867459-c0a57cd8-0b27-11e8-909a-004d798b22a6.png)

If clicked I would assume it would save the data components in the currently open tab. Would it make sense to have a set of checkboxes on the Save dialog that popsup where the specific data components could be selected that should be saved (?).

**Comment by kassin** [comment] 2018-02-06 18:48
The user might want multiple options for saving: saving the cubes, saving the spectrum, saving the plots.

**Comment by brechmos-stsci** [comment] 2018-02-07 15:05
I wonder if the saving cubes, plots and spectrum are different sets of functions.  For instance, there is the save button on the FLUX window above (a matplotlib function).  Saving spectra might be better through the specviz functionality. But... something to discuss.

**Comment by astrofrog** [comment] 2018-02-09 18:37
I've now opened a PR to glue to add a 'Save Data' button: https://github.com/glue-viz/glue/pull/1516

**Comment by brechmos-stsci** [comment] 2018-02-21 18:54
There is now the ability to save cubes from in cubeviz.

**Closed by brechmos-stsci** 2018-02-21 18:54 UTC
